
package javaapplication11;

import java.awt.Component;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import java.util.List;


public class frmemp extends javax.swing.JInternalFrame 
{
     public frmemp()  
     {
        
         try {
             initComponents();
             setLocation(400, 100);
             loaddata();
             clear();             
             DefaultTableColumnModel mod=(DefaultTableColumnModel)jTable1.getColumnModel();
             TableColumn col=mod.getColumn(4);
             col.setCellRenderer(new TableCellRenderer()
             {
                 @Override
                 public Component getTableCellRendererComponent(JTable jtable, Object o, boolean bln, boolean bln1, int i, int i1)
                 {
                     JLabel lbl=new JLabel();
                     //ImageIcon imageIcon = new ImageIcon(new ImageIcon(o).getImage().getScaledInstance(20, 20, Image.SCALE_DEFAULT));
                     
                     lbl.setIcon((ImageIcon)o);
                     lbl.setSize(50,50);
                     return lbl;
                 }
             });
             jTable1.setRowHeight(80);
                     
         } catch (IOException ex) {
             Logger.getLogger(frmemp.class.getName()).log(Level.SEVERE, null, ex);
         } catch (ClassNotFoundException ex) {
             Logger.getLogger(frmemp.class.getName()).log(Level.SEVERE, null, ex);
         } catch (SQLException ex) {
             Logger.getLogger(frmemp.class.getName()).log(Level.SEVERE, null, ex);
         }
    }

             
 
                      
                     
                     
                     /**
                      * This method is called from within the constructor to initialize the form.
                      * WARNING: Do NOT modify this code. The content of this method is always
                      * regenerated by the Form Editor.
                      */
                     @SuppressWarnings("unchecked")
                     // <editor-fold defaultstate="collapsed" desc="Generated Code">
                     
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtnam = new javax.swing.JTextField();
        txtphn = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmbloc = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtpic = new javax.swing.JTextField();
        btnpic = new javax.swing.JButton();
        savebtn = new javax.swing.JButton();
        updatebtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        cancelbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setBorder(null);
        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(204, 0, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText(" Employee Name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText(" Phone Number");

        txtnam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText(" Select Location");

        cmbloc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Patiala", "Chandigarh", "Haryana", "Delhi", "Ludhiana", "Patna", "Kanpur", " " }));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText(" Browse Picture");

        txtpic.setEnabled(false);

        btnpic.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnpic.setText("....");
        btnpic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpicActionPerformed(evt);
            }
        });

        savebtn.setBackground(new java.awt.Color(255, 255, 255));
        savebtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        savebtn.setText("SAVE");
        savebtn.setBorder(null);
        savebtn.setBorderPainted(false);
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });

        updatebtn.setBackground(new java.awt.Color(255, 255, 255));
        updatebtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        updatebtn.setText("UPDATE");
        updatebtn.setBorder(null);
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });

        deletebtn.setBackground(new java.awt.Color(255, 255, 255));
        deletebtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        deletebtn.setText("DELETE");
        deletebtn.setBorder(null);
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });

        cancelbtn.setBackground(new java.awt.Color(255, 255, 255));
        cancelbtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        cancelbtn.setText("CANCEL");
        cancelbtn.setBorder(null);
        cancelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbloc, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtpic, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnpic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtphn, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnam, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(savebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(updatebtn)
                        .addGap(46, 46, 46)
                        .addComponent(deletebtn)
                        .addGap(36, 36, 36)
                        .addComponent(cancelbtn)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtnam))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtphn)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbloc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtpic, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnpic, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(savebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deletebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee No.", "Name", "Phone No.", "Location", "Picture"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setCellSelectionEnabled(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Algerian", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 102));
        jLabel2.setText(" MANAGE EMPLOYEES");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void saveimage()
    {
         try {
             Path source=Paths.get(txtpic.getText());
             Path targetDir=Paths.get("D:\\java\\complaint management\\src\\emppics");
             Files.createDirectories(targetDir);//if dir doesnt exist , create new
             String s=txtpic.getText();
             s=s.substring(s.lastIndexOf("\\")+1);
             Path Target=targetDir.resolve(s);
             Files.copy(source, Target,StandardCopyOption.REPLACE_EXISTING);
         } catch (IOException ex) {
             Logger.getLogger(frmemp.class.getName()).log(Level.SEVERE, null, ex);
         }
    }
    
    private void loaddata() throws IOException,ClassNotFoundException,SQLException,NullPointerException
    {
        DefaultTableModel mod=(DefaultTableModel)(jTable1.getModel());
        clsemp obj=new clsemp();
        List<empprp> k=obj.dspemp();
        mod.setRowCount(0);
        //JOptionPane.showMessageDialog(this,"null entry");
        for(empprp p:k)
        {
            Object[] rowdata=new Object[5];
            rowdata[0]=p.getEmpcod();
            rowdata[1]=p.getEmpnam();
            rowdata[2]=p.getEmpphnno();
            rowdata[3]=p.getEmploc();
            ImageIcon img=new ImageIcon(getClass().getResource("/emppics/"+p.getEmppic()));
            rowdata[4]=img;
            mod.addRow(rowdata);
        }
        
        // JOptionPane.showMessageDialog(this,"bherfk");
        jTable1.setModel(mod);              
    }

     private void clear()
    {
        txtnam.setText("");
        txtphn.setText("");
        txtpic.setText("");
    }
    
    
    
    private void txtnamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        if(txtnam.getText().equals("") || txtphn.getText().equals(""))
      JOptionPane.showMessageDialog(this,"Please fill entries");
      else  
      {
            try {
                empprp objprp=new empprp();
                clsemp obj=new clsemp();
                objprp.setEmpnam(txtnam.getText());
                objprp.setEmpphnno(txtphn.getText());
                objprp.setEmploc(cmbloc.getSelectedItem().toString());
                String s=txtpic.getText();
                if(s.equals("")==true)
                {
                    try {
                        empprp k =obj.findemp(ecod);
                        objprp.setEmppic(k.getEmppic());
                    } catch (IOException ex) {
                        Logger.getLogger(frmemp.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(frmemp.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (SQLException ex) {
                        Logger.getLogger(frmemp.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }else
                {
                    s=s.substring(s.lastIndexOf("\\")+1);
                    objprp.setEmppic(s);
                }
                objprp.setEmpcod(ecod);
                
                obj.updemp(objprp);
                deletebtn.setEnabled(false);
                updatebtn.setEnabled(false);
                 //code to clear boxes and fill table
                saveimage();
                clear();
                loaddata();
                
            } catch (IOException ex) {
                Logger.getLogger(frmemp.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(frmemp.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(frmemp.class.getName()).log(Level.SEVERE, null, ex);
            }
      }
    }//GEN-LAST:event_updatebtnActionPerformed

    private void btnpicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpicActionPerformed
      JFileChooser jf=new JFileChooser();
      jf.setFileSelectionMode(JFileChooser.FILES_ONLY);
      int a=jf.showOpenDialog(this);
      if(a==JFileChooser.APPROVE_OPTION)
          txtpic.setText(jf.getSelectedFile().getAbsolutePath());    
    }//GEN-LAST:event_btnpicActionPerformed

        
    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        if(txtnam.getText()=="" || txtphn.getText()=="")
            JOptionPane.showMessageDialog(this,"Please enter values");
        else
        {
            try {
                clsemp obj=new clsemp();
                empprp objprp=new empprp();
                objprp.setEmpnam(txtnam.getText());
                objprp.setEmpphnno(txtphn.getText());
                objprp.setEmploc(cmbloc.getSelectedItem().toString());
                String s=txtpic.getText();
                s=s.substring(s.lastIndexOf("\\")+1);
                objprp.setEmppic(s);
                obj.insemp(objprp);
                saveimage();
                clear();
                loaddata();
                
            } catch (IOException | ClassNotFoundException | SQLException ex) {
                Logger.getLogger(frmemp.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_savebtnActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
         try {
             clsemp obj=new clsemp();
             empprp objprp=new empprp();
             objprp.setEmpcod(ecod);
             obj.delemp(objprp);
             clear();
             loaddata();
             
             updatebtn.setEnabled(false);
             deletebtn.setEnabled(false);
         } catch (IOException ex) {
             Logger.getLogger(frmemp.class.getName()).log(Level.SEVERE, null, ex);
         } catch (ClassNotFoundException ex) {
             Logger.getLogger(frmemp.class.getName()).log(Level.SEVERE, null, ex);
         } catch (SQLException ex) {
             Logger.getLogger(frmemp.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_deletebtnActionPerformed

    int ecod;
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       int idx=jTable1.getSelectedRow();
       if(idx!=-1)
       {
          ecod=(int)jTable1.getValueAt(idx,0);
    txtnam.setText(jTable1.getValueAt(idx,1).toString());
    txtphn.setText(jTable1.getValueAt(idx,2).toString());
    cmbloc.setSelectedItem(
            jTable1.getValueAt(idx, 3).toString()      
    );
              
          updatebtn.setEnabled(true);
          deletebtn.setEnabled(true);
       }
  
    }//GEN-LAST:event_jTable1MouseClicked

    private void cancelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbtnActionPerformed
        clear();
       updatebtn.setEnabled(false);
       deletebtn.setEnabled(false);
    }//GEN-LAST:event_cancelbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnpic;
    private javax.swing.JButton cancelbtn;
    private javax.swing.JComboBox<String> cmbloc;
    private javax.swing.JButton deletebtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton savebtn;
    private javax.swing.JTextField txtnam;
    private javax.swing.JTextField txtphn;
    private javax.swing.JTextField txtpic;
    private javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables
}
